apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JeremyCurmi/argocd-app-config.git
    targetRevision: HEAD # lastest commit
    path: dev
  destination:
    server: https://kubernetes.default.svc # cluster endpoint (internally for poc)
    namespace: testbrand
  syncPolicy:
    syncOptions:
      - CreateNamespace=true # create namespace if it doesn't exist

    automated: 
      selfHeal:true # will automatically sync the changes to the cluster (even when you do manual changes)
      prune: true # delete resources that are not in the app

